# CC variable for the compiler
CC=g++
# CFLAGS options for the compiler
CXXFLAGS=-O2
LIBS=

all: perpalya2015

perpalya2015: 
	$(CC) $(CXXFLAGS) PrimeCycles.cpp $(LIBS) -o perpalya2015

clean:
	rm -rf *.o perpalya2015